#!/usr/bin/env python
# Time-stamp: <2017-02-22 15:56:53 smathias>
"""Load IDG family and extended family designations into TCRD from text file.

Usage:
    load-IDGFamsExt.py [--debug=<int> | --quiet] [--dbhost=<str>] [--dbname=<str>]
    load-IDGFamsExt.py -h | --help

Options:
  -i --infile INFILE   : Input pickle file containing IDG Family data
  -h --dbhost DBHOST   : MySQL database host name [default: localhost]
  -n --dbname DBNAME   : MySQL database name [default: tcrdev]
  -q --quiet           : set output verbosity to minimal level
  -d --debug DEBUGL    : set debugging output level (0-3) [default: 0]
  -? --help            : print this message and exit 
"""
__author__    = "Steve Mathias"
__email__     = "smathias @salud.unm.edu"
__org__       = "Translational Informatics Division, UNM School of Medicine"
__copyright__ = "Copyright 2017, Steve Mathias"
__license__   = "Creative Commons Attribution-NonCommercial (CC BY-NC)"
__version__   = "1.0.0"

import os,sys,time
from docopt import docopt
from TCRD import DBAdaptor
import csv
from progressbar import *

PROGRAM = os.path.basename(sys.argv[0])
INFILE = '../data/TCRD_3.1.4_TDL_families_Updated.txt'

def main():
  args = docopt(__doc__, version=__version__)
  debug = int(args['--debug'])
  if debug > 1:
    print "\n[*DEBUG*] ARGS:\n%s\n"%repr(args)
  
  dba_params = {'dbhost': args['--dbhost'], 'dbname': args['--dbname'], 'logger_name': __name__}
  dba = DBAdaptor(dba_params)
  dbi = dba.get_dbinfo()
  if not args['--quiet']:
    print "\n%s (v%s) [%s]:" % (PROGRAM, __version__, time.strftime("%c"))
    print "\nConnected to TCRD database %s (schema ver %s; data ver %s)" % (args['--dbname'], dbi['schema_ver'], dbi['data_ver'])

  # Dataset
  dataset_id = dba.ins_dataset( {'name': 'IDG Families', 'source': 'File %s'%os.path.basename(INFILE), 'app': PROGRAM, 'app_version': __version__, 'comments': "Target family designations generated by IDG-KMC groups at UNM and UMiami."} )
  if not dataset_id:
    print "WARNING: Error inserting dataset See logfile %s for details." % logfile
    sys.exit(1)
  # Provenance
  rv = dba.ins_provenance({'dataset_id': dataset_id, 'table_name': 'target', 'column_name': 'tiofam'})
  if not rv:
    print "WARNING: Error inserting provenance. See logfile %s for details." % logfile
    sys.exit(1)
  
  start_time = time.time()
  line_ct = wcl(INFILE)
  if not args['--quiet']:
    print "\nProcessing %d lines in inut file %s" % (line_ct, INFILE)
  pbar_widgets = ['Progress: ',Percentage(),' ',Bar(marker='#',left='[',right=']'),' ',ETA()]
  pbar = ProgressBar(widgets=pbar_widgets, maxval=line_ct).start()
  ct = 0
  upd_ct1 = 0
  upd_ct2 = 0
  null_ct = 0
  notfnd = []
  mulfnd = []
  with open(INFILE, 'rU') as tsv:
    tsvreader = csv.reader(tsv, delimiter='\t')
    header = tsvreader.next() # skip header line
    for row in tsvreader:
      ct += 1
      pbar.update(ct)
      up = row[5].strip()
      fam = row[2].strip()
      famext = row[3].strip()
      if not fam:
        null_ct += 1
        continue
      targets = dba.find_targets({'uniprot': up})
      if not targets:
        notfnd.append(up)
        continue
      if len(targets) > 1:
        mulfnd.append(upd_ct)
        continue
      t = targets[0]
      rv = dba.rv = dba.upd_target(t['id'], 'fam', fam)
      if not rv:
        print "ERROR updating target.fam: %d to %s" % (t['id'], fam)
      else:
        upd_ct1 += 1
      if famext and famext != '':
        rv = dba.upd_target(t['id'], 'famext', famext)
        if not rv:
          print "ERROR updating target.famext: %d to %s" % (t['id'], famext)
        else:
          upd_ct2 += 1
  pbar.finish()
  elapsed = time.time() - start_time
  print "%d rows processed. Elapsed time: %s" % (ct, secs2str(elapsed))
  print "%d IDG family designations loaded into TCRD." % upd_ct1
  print "%d IDG extended family designations loaded into TCRD." % upd_ct2
  if notfnd:
    print "  No target found for %d UniProt accessions: %s" % (len(notfnd), ", ".join(notfnd))
  if mulfnd:
    print "[WARNING] Multiple targets found for %d UniProt accessions: %s" % (len(mulfnd), ", ".join(mulfnd))
  print "\n%s: Done.\n" % PROGRAM
  

def wcl(fname):
  with open(fname) as f:
    for i, l in enumerate(f):
      pass
  return i + 1

def secs2str(t):
  return "%d:%02d:%02d.%03d" % reduce(lambda ll,b : divmod(ll[0],b) + ll[1:], [(t*1000,),1000,60,60])

if __name__ == '__main__':
  main()
